//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImasArchiveLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImasArchiveLib.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of buffer is not a multiple of 8..
        /// </summary>
        internal static string Argument_LengthNotMultipleOf8 {
            get {
                return ResourceManager.GetString("Argument_LengthNotMultipleOf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading and seeking..
        /// </summary>
        internal static string Argument_NotReadAndSeek {
            get {
                return ResourceManager.GetString("Argument_NotReadAndSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value was out of legal range..
        /// </summary>
        internal static string ArgumentOutOfRangeException_Enum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be nonnegative..
        /// </summary>
        internal static string ArgumentOutOfRangeException_Negative {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was greater than length of stream..
        /// </summary>
        internal static string ArgumentOutOfRangeException_StringLength {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading from the decipher stream is not supported..
        /// </summary>
        internal static string CannotReadFromDecipherStream {
            get {
                return ResourceManager.GetString("CannotReadFromDecipherStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to the encipher stream is not supported..
        /// </summary>
        internal static string CannotWriteToEncipherStream {
            get {
                return ResourceManager.GetString("CannotWriteToEncipherStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found invalid data while deciphering..
        /// </summary>
        internal static string GenericInvalidData {
            get {
                return ResourceManager.GetString("GenericInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset plus count is larger than the length of target array..
        /// </summary>
        internal static string InvalidArgumentOffsetCount {
            get {
                return ResourceManager.GetString("InvalidArgumentOffsetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin file header is invalid..
        /// </summary>
        internal static string InvalidData_BinHeader {
            get {
                return ResourceManager.GetString("InvalidData_BinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fbs header is invalid..
        /// </summary>
        internal static string InvalidData_FbsHeader {
            get {
                return ResourceManager.GetString("InvalidData_FbsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fbs key is incorrect..
        /// </summary>
        internal static string InvalidData_FbsKey {
            get {
                return ResourceManager.GetString("InvalidData_FbsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segs file contains invalid data..
        /// </summary>
        internal static string InvalidData_Segs {
            get {
                return ResourceManager.GetString("InvalidData_Segs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segs header is invalid..
        /// </summary>
        internal static string InvalidData_SegsHeader {
            get {
                return ResourceManager.GetString("InvalidData_SegsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry is already currently open for reading..
        /// </summary>
        internal static string IO_EntryAlreadyOpen {
            get {
                return ResourceManager.GetString("IO_EntryAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported..
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute position is not a multiple of 8..
        /// </summary>
        internal static string NotSupported_PosNotMultipleOf8 {
            get {
                return ResourceManager.GetString("NotSupported_PosNotMultipleOf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string NotSupported_UnreadableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support seeking..
        /// </summary>
        internal static string NotSupported_UnseekableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnseekableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support writing..
        /// </summary>
        internal static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed stream..
        /// </summary>
        internal static string ObjectDisposed_StreamClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_StreamClosed", resourceCulture);
            }
        }
    }
}
